[tool.black]
target-version = ['py311']
skip-string-normalization = 1
indent-width = 4

[tool.isort]
profile = "black"
line_length = 120
multi_line_output = 3
include_trailing_comma = true
force_single_line = false
lines_after_imports = 2
skip = ['tutorial-env/*']

[tool.flake8]
max-line-length = 120
exclude = ['.git', '__pycache__', 'tutorial-env', '__init__.py']
ignore = [
    "E203",  # Не проверять пробел перед `:`
    "W503",  # Не проверять разрывы строк
]

[tool.mypy]
python_version = "3.11"             # Целевая версия Python
strict = true                       # Включить строгий режим
disallow_untyped_defs = true        # Запретить неаннотированные функции